# -*- coding: utf-8 -*-
"""Multiple Linear Regression Exercise 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AnE_-RyjDdY8-kTW3jXzRHg8PLbDQvo5
"""

#Import required libraries for data analysis and regression
import seaborn as sns                  #Used for data visualization (optional for exploring patterns)
import numpy as np                     #Used for numerical computations and array handling
import pandas as pd                    #Used for data manipulation and analysis (DataFrame operations)
import statsmodels.api as sm           #Used for statistical modelling (OLS regression, diagnostics)
import statsmodels.formula.api as smf  #Used for formula-based statistical models (alternative syntax)
import matplotlib.pyplot as plt        #Used for plotting and visualization

#Import diagnostic and statistical tools from statsmodels
from statsmodels.stats.outliers_influence import variance_inflation_factor  #It is used to check for multicollinearity between predictors
from statsmodels.stats.diagnostic import het_breuschpagan  #It performs the Breusch–Pagan test for heteroscedasticity)

#Upload and load the dataset into colab
from google.colab import files   #'files' module enables manual file upload into the Colab environment
uploaded = files.upload()  #It promps us to choose a file from our computer.
df = pd.read_csv("cw1.csv")  #Reads the uploaded CSV file ("cw1.csv") into a DataFrame called df.
df.head()  #Displays the first five rows of the dataset for inspection.

#Question 1(a): Properly encode any categorical variables (like SocialClass) with dummy variables.

#Step 1: Inspect categorical variables that need to be encoded
print(df.info())
#The .info() method displays column names, data types, and non-null counts.
#This helps to identify which variables are 'object' or 'category' types that must be converted into dummy (indicator) variables.
print("Unique values in SocialClass:", df['SocialClass'].unique())
#This shows all distinct categories within the SocialClass variable
#(e.g., 'Low', 'Middle', 'High') — which confirms it is a categorical variable.
print("Unique values in SmokingStatus:", df['SmokingStatus'].unique())
#Similarly, this displays the unique categories in SmokingStatus
#(e.g., 'Current', 'Former', 'Never'), which must also be encoded numerically.
#Step 2: Encode categorical variables (SocialClass and SmokingStatus) into dummy variables
df_encoded = pd.get_dummies(df, columns=['SocialClass', 'SmokingStatus'], drop_first=True)
#pd.get_dummies() automatically creates binary (0/1) columns for each category.
#The 'columns' parameter specifies which variables to encode.
#The argument drop_first=True avoids the “dummy variable trap” by omitting one category as a baseline reference, preventing perfect multicollinearity.
df_encoded = df_encoded.astype(int)  # Converts all columns in the encoded DataFrame to integer type,
#Step 3: Verify that encoding worked
print("Columns after encoding:")
print(df_encoded.columns)
#Prints all column names to confirm that dummy variables were added correctly and categorical variables were replaced by their encoded versions.
#Step 4: Display the first few rows of the encoded dataset
df_encoded.head() #Displays the first five rows of the encoded dataset to visually confirm that binary dummy columns have been generated properly.

#Question 1(b): Multiple Linear Regression Model

#Step 1: Define dependent (Y) and independent (X) variables
y = df_encoded['SystolicBloodPressure']
#Step 2: Select the correct independent variables based on encoded columns
X = df_encoded[['Age', 'BMI', 'Cholesterol', 'PhysicalActivity', 'AlcoholUse',
                'SocialClass_Low', 'SocialClass_Middle',
                'SmokingStatus_Former', 'SmokingStatus_Never']]
#Step 3: Add the constant term (intercept)
#This adds a constant column to represent the baseline value when all predictors are zero.
X = sm.add_constant(X)
#Step 4: Fit the model
#We use Ordinary Least Squares (OLS) regression from statsmodels to estimate the coefficients.
#The .fit() method runs the model and stores the results.
model = sm.OLS(y, X).fit()
# Step 5: Summarize results
# The .summary() function displays a detailed regression output including coefficients, significance levels (p-values),
# R-squared and other key statistics for interpretation.
print(model.summary())

#(d)(i) Check Multicollinearity using VIF
#Create a DataFrame for VIF values
#VIF (Variance Inflation Factor) quantifies how much the variance of a
#regression coefficient is inflated due to multicollinearity (high correlation) among predictors.
vif_data = pd.DataFrame()
#Step 2: Store variable names
#The 'Variable' column holds all independent variable names (including the constant term).
vif_data['Variable'] = X.columns
#Step 3: Compute the VIF for each predictor
#The variance_inflation_factor() function from statsmodels calculates VIF for each variable.
#A VIF value above 5 may indicate problematic multicollinearity.
vif_data['VIF'] = [variance_inflation_factor(X.values, i)
                   for i in range(X.shape[1])]
#Step 4: Display the results
print(vif_data)

#(d)(ii) Influential Points via Cook's Distance
#Get influence statistics
influence = model.get_influence()
cooks_d = influence.cooks_distance[0]
#Plot Cook's Distance
plt.figure(figsize=(8,4))  #Plot Cook’s Distance to visualize influential observations
plt.stem(np.arange(len(cooks_d)), cooks_d, markerfmt=",", basefmt=" ")  #The stem plot shows Cook’s distance for each observation index
plt.axhline(y=4/len(X), color='r', linestyle='--', label='Threshold (4/n)') #Add a horizontal reference line for the threshold 4/n
#Add labels and legend for clarity
plt.title("Cook's Distance for Influential Points")
plt.xlabel("Observation Index")
plt.ylabel("Cook's Distance")
plt.legend()
plt.show()
#Identify influential observations
#Observations with Cook’s distance greater than 4/n are typically considered influential.
threshold = 4/len(X)
influential_points = np.where(cooks_d > threshold)[0]
#Print results
#Display the total number of influential observations and their corresponding indices.
print(f"Number of influential points: {len(influential_points)}")
print("Indices of influential points:", influential_points)

#(d)(iii) Heteroscedasticity Test (Breusch–Pagan)
#Step 1: Perform the Breusch–Pagan test for heteroscedasticity
#This test checks whether the variance of residuals from the regression model is
#constant (homoscedastic) or depends on the values of the independent variables (heteroscedastic)
#Null hypothesis (H₀): Homoscedasticity (equal variance of errors)
#Alternative hypothesis (H₁): Heteroscedasticity (unequal variance of errors)
bp_test = het_breuschpagan(model.resid, model.model.exog)
#Step 2: Extract and label the results
#The het_breuschpagan() function returns four values:
#1. Lagrange multiplier statistic (LM)
#2. p-value for the LM statistic
#3. f-value
#4. p-value for the f-statistic
labels = ['Lagrange multiplier statistic', 'p-value', 'f-value', 'f p-value']
bp_results = dict(zip(labels, bp_test))
# Step 3: Print the results in a clear and readable format
print("Breusch–Pagan Test Results:")
for key, value in bp_results.items():
    print(f"{key}: {value:.4f}")

#(e) Remedies
#Re-create X and y (full model) to ensure variables are in the environment
y = df_encoded['SystolicBloodPressure']
X = df_encoded[['Age', 'BMI', 'Cholesterol', 'PhysicalActivity', 'AlcoholUse',
                'SocialClass_Low', 'SocialClass_Middle',
                'SmokingStatus_Former', 'SmokingStatus_Never']]
import statsmodels.api as sm
X = sm.add_constant(X)
model = sm.OLS(y, X).fit()
#Fit model with heteroskedasticity-consistent standard errors (HC3)
model_hc3 = model.get_robustcov_results(cov_type='HC3')
#HC3 is conservative and often recommended for small samples / influential points
#Print side-by-side: original and robust summary
print("Original OLS summary:")
print(model.summary())
print("\nOLS with HC3 robust standard errors:")
print(model_hc3.summary())

import numpy as np
#Influence measures (if not computed)
influence = model.get_influence()
cooks_d = influence.cooks_distance[0]
#Identify influential indices (4/n threshold)
n = len(df_encoded)
threshold = 4/n
influential_points = np.where(cooks_d > threshold)[0]
print("Threshold (4/n):", threshold)
print("Number of influential points:", len(influential_points))
print("Indices:", influential_points)
#Sensitivity re-fit: model without influential observations (for reporting only)
mask = np.ones(n, dtype=bool)
mask[influential_points] = False
X_sens = X[mask]
y_sens = y[mask]
model_sens = sm.OLS(y_sens, X_sens).fit()
print("Sensitivity model (excluding influential points) summary:")
print(model_sens.summary())
#Also compute robust SEs for the sensitivity model
model_sens_hc3 = model_sens.get_robustcov_results(cov_type='HC3')
print("Sensitivity model (HC3):")
print(model_sens_hc3.summary())

from statsmodels.robust.robust_linear_model import RLM
from statsmodels.robust.norms import HuberT
#Fit an RLM model (HuberT) as a robustness check — downweights outliers
rlm_model = RLM(y, X, M=HuberT()).fit()
print("Robust regression (RLM, HuberT) summary:")
print(rlm_model.summary())

# Simple bootstrap for coefficient CIs (nonparametric)
import numpy as np
n_boot = 2000
coefs = np.zeros((n_boot, X.shape[1]))  # store bootstrap coefficients
for i in range(n_boot):
    idx = np.random.choice(np.arange(n), size=n, replace=True)
    Xb = X.values[idx]
    yb = y.values[idx]
    try:
        coef_b = np.linalg.lstsq(Xb, yb, rcond=None)[0]  # OLS closed-form
        coefs[i, :] = coef_b
    except Exception:
        coefs[i, :] = np.nan
# Compute percentile 95% CI
coef_names = X.columns
ci_lower = np.nanpercentile(coefs, 2.5, axis=0)
ci_upper = np.nanpercentile(coefs, 97.5, axis=0)
bootstrap_ci = pd.DataFrame({'coef': model.params.values, 'ci_lower': ci_lower, 'ci_upper': ci_upper}, index=coef_names)
print("Bootstrap 95% CIs:")
print(bootstrap_ci)